####  APPLICATION DETAILS  ####
spring.application.name=logging-service
server.port=${SERVER_PORT:9091}
####  DB INFO  ####
spring.data.mongodb.host=${DATABASE_HOST:localhost}
spring.data.mongodb.port=27017
spring.data.mongodb.database=public_db
spring.data.mongodb.username=public_user
spring.data.mongodb.password=publicN3xt!
spring.data.mongodb.authentication-database=admin
#### LOGGING ####
logging.level.com.publicnext=INFO
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.springframework.boot.autoconfigure=WARN
logging.level.org.springframework.context=WARN
logging.level.org.springframework.security=INFO
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql=ERROR
