####  APPLICATION DETAILS  ####
spring.application.name=order-management
server.port=${SERVER_PORT:9090}
####  DB INFO  ####
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:public_db}
spring.datasource.username=${DATABASE_USERNAME:public_user}
spring.datasource.password=${DATABASE_PASSWORD:publicN3xt!}
####  LIQUIBASE  ####
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
#### LOGGING ####
logging.level.com.publicnext=INFO
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.springframework.boot.autoconfigure=WARN
logging.level.org.springframework.context=WARN
logging.level.org.springframework.security=INFO
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql=ERROR

#### SCHEDULER ####
scheduler.process.orders.cron=0 * * * * *

### REST ###
logging.service.url=${LOGGING_SERVICE_URL:localhost:9091}